name:                santorini
version:             0.1.0.0
github:              "stormymcstorm/santorini"
license:             BSD3
author:              "Carson Storm"
maintainer:          "carson.storm@outlook.com"
copyright:           "2021 Carson Storm"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/stormymcstorm/santorini#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.5.5
- vector
- array 
- bytestring
- utf8-string

library:
  source-dirs: src

executables:
  santorini-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santorini

# tests:
#   santorini-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - santorini
